version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.12
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: pytest --cov=hw1 --cov-report=term-missing

  build-and-push:
    docker:
      - image: docker:20.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: docker build -t parthj10/hw1-api .
      - run:
          name: Push Docker Image
          command: |
            echo Sonic@500 | docker login -u parthj10 --password-stdin
            docker push parthj10/hw1-api

workflows:
  version: 2
  test-and-deploy:
    jobs:
      - test
      - build-and-push:
          requires:
            - test
