version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.12
    steps:
      - checkout

      # Set up Python environment
      - run:
          name: Install Dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      # Run tests with coverage
      - run:
          name: Run Tests
          command: pytest --cov=hw1 --cov-report=term-missing

      # Save coverage report as an artifact
      - store_artifacts:
          path: .coverage
          destination: coverage-report

workflows:
  version: 2
  test-workflow:
    jobs:
      - test
